Output assets/gitnine.mp4

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1920
Set Height 1080

Type "./apps/gitnine.py"
Enter
Enter
Sleep 1s
Type ":branch" Sleep 500ms  Enter
Sleep 500ms
Enter
Type@1s "jjjjkkkk"
Type@1s "h"
Sleep 1s
Type@1s "jjjjkkkk"
Type@1s "a"
Sleep 1500ms
Type@2s "hah"
Enter
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 5s
Escape
Sleep 2s
Escape
Sleep 2s
Escape
Sleep 2s

