Output assets/gitnine.mp4
Output assets/gitnine.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1920
Set Height 1080
Set Theme 'Dracula'

Type "NINES_SCREENKEY=1 ./apps/gitnine.py"
Enter
Enter
Hide
Sleep 5s
Show
Type ":branch" Sleep 500ms  Enter
Sleep 500ms
Enter
Type@1s "jjjjkkkk"
Type@1s "h"
Sleep 1s
Type@1s "jjjjkkkk"
Type@1s "a"
Sleep 1500ms
Type@2s "hah"
Enter
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 5s
Escape
Sleep 2s
Escape
Sleep 2s
Escape
Sleep 2s

