Output assets/global-commands.mp4
Output assets/global-commands.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1920
Set Height 1080
Set Theme 'Dracula'

Hide
Type "NINES_SCREENKEY=1 ./apps/swapi.py"
Enter
Sleep 5s
Show
Type ":person"
Sleep 250ms
Enter
Sleep 5s
Type@250ms "jjjjjj"
Sleep 500ms
Type ":film"
Sleep 250ms
Enter
Sleep 5s
Type ":Film"
Sleep 250ms
Enter
Sleep 5s
Type@250ms "ajjjjjjkkkkkkk"
Sleep 5s
