Output assets/swapi.mp4
Output assets/swapi.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1920
Set Height 1080
Set Theme 'Dracula'

Type "NINES_SCREENKEY=1 ./apps/swapi.py"
Enter
Sleep 2s
Type ":person"
Sleep 250ms
Enter
Sleep 5s
Type@1s "jjjjkkkk"
Sleep 5s
Type@250ms "jjjjjj"
Sleep 500ms
Type ":film"
Sleep 1s
Enter
Sleep 5s
Type@1s "jjjjkkkk"
Sleep 2s
Type ":vehicle"
Sleep 1s
Enter
Sleep 5s


